Handle web layer offline
Anirudh94/boreas pull request #24
Opened 2017-02-09 19:12 UTC by andrewazores

SSIA. Addresses Issue #20. The server node application handles the web-layer connection failure by logging it and propagating a status 500 to the client application's request. Then the client simply shows "Update failed" type alerts at this point and controllers cancel future updates (this is not new to this PR).

2017-02-17 13:40 UTC, jiekang commented on server/public/js/common/application-service.js
> -    createPrefixedString(str) {
For what it's worth my fix was to call:

this.createPrefixedString(msg)

Which do you prefer? I kind of liked the function but to be honest it's such a small detail, it doesn't matter.

2017-02-17 16:11 UTC, andrewazores commented
Yea, either way. I figured there doesn't seem to be much reason to expose that function to everyone who has an ApplicationService instance, so I got rid of it at the same time. I wouldn't be opposed to adding it back though.

2017-02-21 17:49 UTC, jiekang requested changes

2017-02-21 17:49 UTC, jiekang commented on server/index.js
> -  http.request(options, cpuRes => {
I also had a fix here to handle the situation where the http response is chunked (returned over multiple calls for serverRes.on('data') in this case).

app.get(['/plugins/*', '/api/*'], (req, res) => {
  var options = {
    hostname: '127.0.0.1',
    port: '8090',
    path: req.originalUrl,
    method: 'GET'
  }

  http.request(options, webRes => {
    webRes.setEncoding('utf8');

    let rawData = '';

    webRes.on('data', chunk => {
      rawData += chunk;
    });

    return webRes.on('end', ()=> {
        res.send(rawData);
    });
  }).end();

});


Basically adds data continuously and then on 'end', sends it.

Can you incorporate this change as well?

I can merge after.

2017-02-21 19:48 UTC, andrewazores commented on server/index.js
> -  http.request(options, cpuRes => {
Thanks, I've just added that too.

2017-02-27 17:57 UTC, jiekang approved these changes

2017-02-27 17:57 UTC, merged